[
    $parameters: []
    $variables: [
        $bar
        $foo
        $$index-1
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
    $procedures: [
        $setSubcomponent
    ]($type: /bali/collections/Set/v1)
    $addresses: [
        "1.EvaluateStatement": 1
        "2.EvaluateStatement": 3
    ]
    $instructions: "
        1.EvaluateStatement:
        LOAD VARIABLE $bar
        STORE VARIABLE $foo
        
        2.EvaluateStatement:
        PUSH LITERAL `5`
        STORE VARIABLE $$index-1
        INVOKE $list
        LOAD VARIABLE $$index-1
        INVOKE $addItem WITH 2 ARGUMENTS
        EXECUTE $setSubcomponent ON TARGET WITH ARGUMENTS
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '6001800228018003A04A6003B001D8016004E000'(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
