[
    $source: {
        [
            $foo: $bar
            $baz: 5
        ]
        variable
        isZero(13)
        (a + b) * c
        @reference
        customer[$order, $item, 5]
        list.addItem(item)
        23!
        2 ^ 8
        -π
        *(3, 4i)
        x * y
        a / b
        c // d
        x + y
        w - z
        |(3, 4i)|
        a < b
        c = d
        f > g
        h IS j
        k MATCHES m
        NOT p
        a AND b
        c SANS d
        f XOR g
        h OR j
        foo ? 5
    }
    $parameters: []
    $variables: [
        $a
        $b
        $c
        $customer
        $d
        $f
        $foo
        $g
        $h
        $$index-2
        $item
        $j
        $k
        $list
        $$location-1
        $m
        $p
        $reference
        $$result
        $target
        $variable
        $w
        $x
        $y
        $z
    ]($type: /bali/collections/Set/v1)
    $messages: [
        $addItem
        $getMagnitude
        $getSubcomponent
    ]($type: /bali/collections/Set/v1)
    $addresses: [
        "1.EvaluateStatement": 1
        "2.EvaluateStatement": 11
        "3.EvaluateStatement": 13
        "4.EvaluateStatement": 16
        "5.EvaluateStatement": 22
        "6.EvaluateStatement": 26
        "7.EvaluateStatement": 42
        "8.EvaluateStatement": 48
        "9.EvaluateStatement": 51
        "10.EvaluateStatement": 55
        "11.EvaluateStatement": 58
        "12.EvaluateStatement": 61
        "13.EvaluateStatement": 65
        "14.EvaluateStatement": 69
        "15.EvaluateStatement": 73
        "16.EvaluateStatement": 77
        "17.EvaluateStatement": 81
        "18.EvaluateStatement": 84
        "19.EvaluateStatement": 88
        "20.EvaluateStatement": 92
        "21.EvaluateStatement": 96
        "22.EvaluateStatement": 100
        "23.EvaluateStatement": 104
        "24.EvaluateStatement": 107
        "25.EvaluateStatement": 111
        "26.EvaluateStatement": 115
        "27.EvaluateStatement": 119
        "28.EvaluateStatement": 123
    ]
    $instructions: "
        1.EvaluateStatement:
        INVOKE $catalog
        PUSH LITERAL `$foo`
        PUSH LITERAL `$bar`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        PUSH LITERAL `$baz`
        PUSH LITERAL `5`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        2.EvaluateStatement:
        LOAD VARIABLE $variable
        STORE VARIABLE $$result
        
        3.EvaluateStatement:
        PUSH LITERAL `13`
        INVOKE $isZero WITH 1 ARGUMENT
        STORE VARIABLE $$result
        
        4.EvaluateStatement:
        LOAD VARIABLE $a
        LOAD VARIABLE $b
        INVOKE $sum WITH 2 ARGUMENTS
        LOAD VARIABLE $c
        INVOKE $product WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        5.EvaluateStatement:
        LOAD VARIABLE $reference
        STORE VARIABLE $$location-1
        LOAD DOCUMENT $$location-1
        STORE VARIABLE $$result
        
        6.EvaluateStatement:
        LOAD VARIABLE $customer
        INVOKE $list
        PUSH LITERAL `$order`
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $getSubcomponent TO COMPONENT WITH ARGUMENTS
        INVOKE $list
        PUSH LITERAL `$item`
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $getSubcomponent TO COMPONENT WITH ARGUMENTS
        PUSH LITERAL `5`
        STORE VARIABLE $$index-2
        INVOKE $list
        LOAD VARIABLE $$index-2
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $getSubcomponent TO COMPONENT WITH ARGUMENTS
        STORE VARIABLE $$result
        
        7.EvaluateStatement:
        LOAD VARIABLE $list
        INVOKE $list
        LOAD VARIABLE $item
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $addItem TO COMPONENT WITH ARGUMENTS
        STORE VARIABLE $$result
        
        8.EvaluateStatement:
        PUSH LITERAL `23`
        INVOKE $factorial WITH 1 ARGUMENT
        STORE VARIABLE $$result
        
        9.EvaluateStatement:
        PUSH LITERAL `2`
        PUSH LITERAL `8`
        INVOKE $exponential WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        10.EvaluateStatement:
        PUSH LITERAL `π`
        INVOKE $inverse WITH 1 ARGUMENT
        STORE VARIABLE $$result
        
        11.EvaluateStatement:
        PUSH LITERAL `(3, 4i)`
        INVOKE $conjugate WITH 1 ARGUMENT
        STORE VARIABLE $$result
        
        12.EvaluateStatement:
        LOAD VARIABLE $x
        LOAD VARIABLE $y
        INVOKE $product WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        13.EvaluateStatement:
        LOAD VARIABLE $a
        LOAD VARIABLE $b
        INVOKE $quotient WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        14.EvaluateStatement:
        LOAD VARIABLE $c
        LOAD VARIABLE $d
        INVOKE $remainder WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        15.EvaluateStatement:
        LOAD VARIABLE $x
        LOAD VARIABLE $y
        INVOKE $sum WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        16.EvaluateStatement:
        LOAD VARIABLE $w
        LOAD VARIABLE $z
        INVOKE $difference WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        17.EvaluateStatement:
        PUSH LITERAL `(3, 4i)`
        SEND $getMagnitude TO COMPONENT
        STORE VARIABLE $$result
        
        18.EvaluateStatement:
        LOAD VARIABLE $a
        LOAD VARIABLE $b
        INVOKE $isLess WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        19.EvaluateStatement:
        LOAD VARIABLE $c
        LOAD VARIABLE $d
        INVOKE $areEqual WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        20.EvaluateStatement:
        LOAD VARIABLE $f
        LOAD VARIABLE $g
        INVOKE $isMore WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        21.EvaluateStatement:
        LOAD VARIABLE $h
        LOAD VARIABLE $j
        INVOKE $areSame WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        22.EvaluateStatement:
        LOAD VARIABLE $k
        LOAD VARIABLE $m
        INVOKE $doesMatch WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        23.EvaluateStatement:
        LOAD VARIABLE $p
        INVOKE $not WITH 1 ARGUMENT
        STORE VARIABLE $$result
        
        24.EvaluateStatement:
        LOAD VARIABLE $a
        LOAD VARIABLE $b
        INVOKE $and WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        25.EvaluateStatement:
        LOAD VARIABLE $c
        LOAD VARIABLE $d
        INVOKE $sans WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        26.EvaluateStatement:
        LOAD VARIABLE $f
        LOAD VARIABLE $g
        INVOKE $xor WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        27.EvaluateStatement:
        LOAD VARIABLE $h
        LOAD VARIABLE $j
        INVOKE $or WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        
        28.EvaluateStatement:
        LOAD VARIABLE $foo
        PUSH LITERAL `5`
        INVOKE $default WITH 2 ARGUMENTS
        STORE VARIABLE $$result
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '
        A01428012802B00BB00128032804B00BB0018013601580132805A83F8013
        60016002B0796003B05A80136012800F780F80136004A0492806B001C803
        A0492807B001C8032804800AA049600AB001C8038013600EA049600BB001
        C80180132808A82980132809280AB0278013280BA8378013280CA81A8013
        60176018B05A801360016002B05D801360036005B062801360176018B079
        801360166019B0218013280CC002801360016002B03A801360036005B008
        801360066008B03B80136009600CB0098013600D6010B02380136011A84E
        801360016002B004801360036005B06D801360066008B08680136009600C
        B051801360072804B01F80136013E000
    '(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
