[
    $source: {
        if true then {
            yes
        } else if false then {
            no
        }
    }
    $instructions: "
        1.IfStatement:
        SKIP INSTRUCTION
        
        1.1.ConditionClause:
        PUSH LITERAL `true`
        JUMP TO 1.2.ConditionClause ON FALSE
        
        1.1.1.EvaluateStatement:
        LOAD VARIABLE $yes
        STORE VARIABLE $$result
        
        1.1.ConditionClauseDone:
        JUMP TO 1.IfStatementDone
        
        1.2.ConditionClause:
        PUSH LITERAL `false`
        JUMP TO 1.IfStatementDone ON FALSE
        
        1.2.1.EvaluateStatement:
        LOAD VARIABLE $no
        STORE VARIABLE $$result
        
        1.IfStatementDone:
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '00002801180760048002000B2802180B600180026002E000'(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
    $addresses: [
        "1.IfStatement": 1
        "1.1.ConditionClause": 2
        "1.1.1.EvaluateStatement": 4
        "1.1.ConditionClauseDone": 6
        "1.2.ConditionClause": 7
        "1.2.1.EvaluateStatement": 9
        "1.IfStatementDone": 11
    ]
    $messages: []($type: /bali/collections/Set/v1)
    $parameters: []
    $variables: [
        $no
        $$result
        $target
        $yes
    ]($type: /bali/collections/Set/v1)
]
