[
    $parameters: []
    $variables: [
        $document
        $documents
        $index
        $$index-5
        $$index-7
        $$index-9
        $$location-1
        $$location-10
        $$location-2
        $$location-3
        $$location-4
        $$location-6
        $$location-8
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
    $messages: [
        $getSubcomponent
        $setSubcomponent
    ]($type: /bali/collections/Set/v1)
    $addresses: [
        "1.CheckoutStatement": 1
        "2.SaveStatement": 6
        "3.CommitStatement": 10
        "4.CheckoutStatement": 14
        "5.SaveStatement": 24
        "6.CommitStatement": 34
        "7.DiscardStatement": 44
    ]
    $instructions: "
        1.CheckoutStatement:
        PUSH LITERAL `$document`
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-1
        LOAD DOCUMENT $$location-1
        STORE VARIABLE $document
        
        2.SaveStatement:
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-2
        LOAD VARIABLE $document
        STORE DRAFT $$location-2
        
        3.CommitStatement:
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-3
        LOAD VARIABLE $document
        STORE DOCUMENT $$location-3
        
        4.CheckoutStatement:
        LOAD VARIABLE $documents
        LOAD VARIABLE $index
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-4
        LOAD DOCUMENT $$location-4
        STORE VARIABLE $$index-5
        INVOKE $list
        LOAD VARIABLE $$index-5
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $setSubcomponent TO COMPONENT WITH ARGUMENTS
        
        5.SaveStatement:
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-6
        LOAD VARIABLE $documents
        LOAD VARIABLE $index
        STORE VARIABLE $$index-7
        INVOKE $list
        LOAD VARIABLE $$index-7
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $getSubcomponent TO COMPONENT WITH ARGUMENTS
        STORE DRAFT $$location-6
        
        6.CommitStatement:
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-8
        LOAD VARIABLE $documents
        LOAD VARIABLE $index
        STORE VARIABLE $$index-9
        INVOKE $list
        LOAD VARIABLE $$index-9
        INVOKE $addItem WITH 2 ARGUMENTS
        SEND $getSubcomponent TO COMPONENT WITH ARGUMENTS
        STORE DOCUMENT $$location-8
        
        7.DiscardStatement:
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$location-10
        PUSH LITERAL `none`
        STORE DRAFT $$location-10
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '
        2801280280077807800128028009600190092802800A6001980A60026003
        2802800B780B8004A04A6004B001C8022802800C600260038005A04A6005
        B001C801900C2802800D600260038006A04A6006B001C801980D28028008
        28039008600EE000
    '(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
