[
    $source: {
        none
    }
    $parameters: []
    $variables: [
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
    $messages: []($type: /bali/collections/Set/v1)
    $addresses: [
        "1.EvaluateStatement": 1
    ]
    $instructions: "
        1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $$result
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '280180016001E000'(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
