[
    $parameters: []
    $variables: [
        $error
        $message
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
    $messages: []($type: /bali/collections/Set/v1)
    $addresses: [
        "1.PostStatement": 1
        "1.PostStatementDone": 4
        "1.PostStatementHandlers": 6
        "1.1.HandleClause": 7
        "1.1.1.EvaluateStatement": 18
        "1.1.HandleClauseDone": 20
        "1.2.HandleClause": 21
        "1.2.1.EvaluateStatement": 32
        "1.2.HandleClauseDone": 34
        "1.PostStatementFailed": 35
        "1.PostStatementSucceeded": 36
    ]
    $instructions: "
        1.PostStatement:
        PUSH HANDLER 1.PostStatementHandlers
        LOAD VARIABLE $message
        PUSH LITERAL `<bali:/queues/myqueue>`
        
        1.PostStatementDone:
        POP HANDLER
        JUMP TO 1.PostStatementSucceeded
        
        1.PostStatementHandlers:
        SKIP INSTRUCTION
        
        1.1.HandleClause:
        STORE VARIABLE $error
        LOAD VARIABLE $error
        LOAD VARIABLE $error
        INVOKE $catalog
        PUSH LITERAL `$type`
        PUSH LITERAL `"bad"`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        INVOKE $doesMatch WITH 2 ARGUMENTS
        JUMP TO 1.2.HandleClause ON FALSE
        POP COMPONENT
        
        1.1.1.EvaluateStatement:
        PUSH LITERAL `any`
        STORE VARIABLE $$result
        
        1.1.HandleClauseDone:
        JUMP TO 1.PostStatementSucceeded
        
        1.2.HandleClause:
        STORE VARIABLE $error
        LOAD VARIABLE $error
        LOAD VARIABLE $error
        INVOKE $catalog
        PUSH LITERAL `$type`
        PUSH LITERAL `"horrid"`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        INVOKE $doesMatch WITH 2 ARGUMENTS
        JUMP TO 1.PostStatementFailed ON FALSE
        POP COMPONENT
        
        1.2.1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $$result
        
        1.2.HandleClauseDone:
        JUMP TO 1.PostStatementSucceeded
        
        1.PostStatementFailed:
        HANDLE EXCEPTION
        
        1.PostStatementSucceeded:
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '
        200660022801400000240000800160016001A01428022803B00BB001B023
        18154800280480030024800160016001A01428022805B00BB001B0231823
        4800280680030024E8006003E000
    '(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
