[
    $parameters: []
    $variables: [
        $$eventQueue
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
    $messages: []($type: /bali/collections/Set/v1)
    $addresses: [
        "1.PublishStatement": 1
    ]
    $instructions: "
        1.PublishStatement:
        INVOKE $catalog
        PUSH LITERAL `$type`
        PUSH LITERAL `$changeEvent`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        PUSH LITERAL `$key`
        PUSH LITERAL `$foo`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        PUSH LITERAL `$value`
        PUSH LITERAL `5`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        STORE MESSAGE $$eventQueue
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '
        A01128012802B008B00128032804B008B00128052806B008B00188016002
        E000
    '(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
