[
    $source: {
        post [
            $foo: "bar"
        ] on <bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>
    }
    $instructions: "
        1.PostStatement:
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        STORE VARIABLE $$queue-1
        INVOKE $catalog
        PUSH LITERAL `$foo`
        PUSH LITERAL `"bar"`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        STORE MESSAGE $$queue-1
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '28018001A01428022803B00BB00188016002E000'(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
    $addresses: [
        "1.PostStatement": 1
    ]
    $messages: []($type: /bali/collections/Set/v1)
    $parameters: []
    $variables: [
        $$queue-1
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
]
