[
    $parameters: []
    $variables: [
        $$result
        $target
    ]($type: /bali/collections/Set/v1)
    $messages: []($type: /bali/collections/Set/v1)
    $addresses: [
        "1.PostStatement": 1
    ]
    $instructions: "
        1.PostStatement:
        INVOKE $catalog
        PUSH LITERAL `$foo`
        PUSH LITERAL `"bar"`
        INVOKE $association WITH 2 ARGUMENTS
        INVOKE $addItem WITH 2 ARGUMENTS
        PUSH LITERAL `<bali:MJ0YKAX450LD84TCFJ7CNJ5CX8ZAPZ1Qv3.1>`
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: 'A01428012802B00BB00128036001E000'(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
