[
    $source: {
        select $selection from "alpha" do {
            none
        } "beta" do {
            none
        } "gamma" do {
            none
        } else {
            none
        }
    }
    $instructions: "
        1.SelectStatement:
        PUSH LITERAL `$selection`
        STORE VARIABLE $$selector-1
        
        1.1.OptionClause:
        LOAD VARIABLE $$selector-1
        PUSH LITERAL `"alpha"`
        INVOKE $doesMatch WITH 2 ARGUMENTS
        JUMP TO 1.2.OptionClause ON FALSE
        
        1.1.1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $$result
        
        1.1.OptionClauseDone:
        JUMP TO 1.SelectStatementDone
        
        1.2.OptionClause:
        LOAD VARIABLE $$selector-1
        PUSH LITERAL `"beta"`
        INVOKE $doesMatch WITH 2 ARGUMENTS
        JUMP TO 1.3.OptionClause ON FALSE
        
        1.2.1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $$result
        
        1.2.OptionClauseDone:
        JUMP TO 1.SelectStatementDone
        
        1.3.OptionClause:
        LOAD VARIABLE $$selector-1
        PUSH LITERAL `"gamma"`
        INVOKE $doesMatch WITH 2 ARGUMENTS
        JUMP TO 1.4.ElseClause ON FALSE
        
        1.3.1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $$result
        
        1.3.OptionClauseDone:
        JUMP TO 1.SelectStatementDone
        
        1.4.ElseClause:
        SKIP INSTRUCTION
        
        1.4.1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $$result
        
        1.4.ElseClauseDone:
        JUMP TO 1.SelectStatementDone
        
        1.SelectStatementDone:
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '
        2801800260022802B023180A28038001001C60022804B023181128038001
        001C60022805B023181828038001001C000028038001001C6001E000
    '(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
    $addresses: [
        "1.SelectStatement": 1
        "1.1.OptionClause": 3
        "1.1.1.EvaluateStatement": 7
        "1.1.OptionClauseDone": 9
        "1.2.OptionClause": 10
        "1.2.1.EvaluateStatement": 14
        "1.2.OptionClauseDone": 16
        "1.3.OptionClause": 17
        "1.3.1.EvaluateStatement": 21
        "1.3.OptionClauseDone": 23
        "1.4.ElseClause": 24
        "1.4.1.EvaluateStatement": 25
        "1.4.ElseClauseDone": 27
        "1.SelectStatementDone": 28
    ]
    $messages: []($type: /bali/collections/Set/v1)
    $parameters: []
    $variables: [
        $$result
        $$selector-1
        $target
    ]($type: /bali/collections/Set/v1)
]
