[
    $parameters: []
    $variables: [
        $$iterator-1
        $$result
        $symbol
        $target
        $x
        $y
        $z
    ]($type: /bali/collections/Set/v1)
    $procedures: [
        $getIterator
        $getNext
        $hasNext
    ]($type: /bali/collections/Set/v1)
    $addresses: [
        "1.WithStatement": 1
        "1.1.ConditionClause": 4
        "1.1.1.EvaluateStatement": 10
        "1.1.2.IfStatement": 12
        "1.1.2.1.ConditionClause": 13
        "1.1.2.1.1.EvaluateStatement": 15
        "1.1.2.1.2.ContinueStatement": 17
        "1.1.2.IfStatementDone": 18
        "1.1.3.EvaluateStatement": 19
        "1.ConditionRepeat": 21
        "1.WithStatementDone": 22
    ]
    $instructions: "
        1.WithStatement:
        PUSH LITERAL `$sequence`
        EXECUTE $getIterator ON TARGET
        STORE VARIABLE $$iterator-1
        
        1.1.ConditionClause:
        LOAD VARIABLE $$iterator-1
        EXECUTE $hasNext ON TARGET
        JUMP TO 1.WithStatementDone ON FALSE
        LOAD VARIABLE $$iterator-1
        EXECUTE $getNext ON TARGET
        STORE VARIABLE $symbol
        
        1.1.1.EvaluateStatement:
        PUSH LITERAL `true`
        STORE VARIABLE $x
        
        1.1.2.IfStatement:
        SKIP INSTRUCTION
        
        1.1.2.1.ConditionClause:
        LOAD VARIABLE $x
        JUMP TO 1.1.2.IfStatementDone ON FALSE
        
        1.1.2.1.1.EvaluateStatement:
        PUSH LITERAL `none`
        STORE VARIABLE $y
        
        1.1.2.1.2.ContinueStatement:
        JUMP TO 1.1.ConditionClause
        
        1.1.2.IfStatementDone:
        SKIP INSTRUCTION
        
        1.1.3.EvaluateStatement:
        PUSH LITERAL `any`
        STORE VARIABLE $z
        
        1.ConditionRepeat:
        JUMP TO 1.1.ConditionClause
        
        1.WithStatementDone:
        LOAD VARIABLE $$result
        HANDLE RESULT
    "($mediatype: "application/basm")
    $bytecode: '
        2801D00180016001D00318166001D0028003280280050000600518122803
        8006000400002804800700046002E000
    '(
        $encoding: $base16
        $mediatype: "application/bcod"
    )
]
