[
    $literals: []
    $constants: [:]
    $procedures: [
        $areEqual: [
            $parameters: [
                $first
                $second
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                PUSH PARAMETER $first
                PUSH PARAMETER $second
                INVOKE $areEqual WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '38013802B008E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $areSame: [
            $parameters: [
                $first
                $second
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                PUSH PARAMETER $first
                PUSH PARAMETER $second
                INVOKE $areSame WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '38013802B009E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $comparison: [
            $parameters: [
                $first
                $second
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                PUSH PARAMETER $first
                PUSH PARAMETER $second
                INVOKE $comparison WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '38013802B016E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $duplicate: [
            $parameters: [
                $component
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                PUSH PARAMETER $component
                INVOKE $duplicate WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '3801A824E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $hash: [
            $parameters: [
                $component
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                PUSH PARAMETER $component
                INVOKE $hash WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '3801A82DE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $doesMatch: [
            $parameters: [
                $component
                $pattern
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                PUSH PARAMETER $component
                PUSH PARAMETER $pattern
                INVOKE $doesMatch WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '38013802B023E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
    ]
](
    $type: /bali/types/Compilation/v1
    $tag: #6NMPX2NN2VDHB27PQC513JBHZHP5317X
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
