[
    $description: "
        This abstract class defines the procedures for the messages that all elemental components
        support.
    "($mediatype: "application/bsmd")
    $parent: /bali/abstractions/Component/v1
    $constants: [:]
    $procedures: [:]
    $literals: []
](
    $name: /bali/abstractions/Element/v1
    $type: /bali/abstractions/Class/v1($existence: $abstract)
    $tag: #3HX8AFPGP3N98J875TV7NNDFSBF7XRJH
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
