[
    $literals: [
        0
    ]
    $constants: [:]
    $procedures: [
        $asBoolean: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $procedures: [
                $asNumeric
            ]($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                EXECUTE $asNumeric ON TARGET
                PUSH LITERAL `0`
                INVOKE $isMoreThan WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001D0012801B043E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $asNumeric: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $procedures: [
                $getSize
            ]($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                EXECUTE $getSize ON TARGET
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001D001E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $getIterator: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $procedures: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $getIterator WITH ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001FFFFE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $getSize: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $procedures: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $getSize WITH ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A835E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $isEmpty: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $procedures: [
                $getSize
            ]($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                EXECUTE $getSize ON TARGET
                PUSH LITERAL `0`
                INVOKE $isMoreThan WITH 2 ARGUMENTS
                INVOKE $complement WITH ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001D0012801B043A80FE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
    ]
](
    $type: /bali/types/Compilation/v1
    $tag: #H9ABCGAL6K9YQX5GDJZSQF0AYVL1LK23
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
