[
    $literals: [
        0
    ]
    $constants: [:]
    $procedures: [
        $asBoolean: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: [
                $asNumeric
            ]($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                SEND $asNumeric TO COMPONENT
                PUSH LITERAL `0`
                INVOKE $more WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001C0012801B04EE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $asNumeric: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: [
                $getSize
            ]($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                SEND $getSize TO COMPONENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001C001E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $getIterator: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $iterator WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A844E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $getSize: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $size WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A876E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $isEmpty: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $size WITH 1 ARGUMENT
                PUSH LITERAL `0`
                INVOKE $more WITH 2 ARGUMENTS
                INVOKE $complement WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A8762801B04EA814E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
    ]
](
    $type: /bali/types/Compilation/v1
    $tag: #H9ABCGAL6K9YQX5GDJZSQF0AYVL1LK23
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
