[
    $literals: []
    $constants: [:]
    $procedures: [
        $ancestry: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $ancestry WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A803E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $interfaces: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $interfaces WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A836E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $isParameterized: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $isParameterized WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A83CE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $isType: [
            $parameters: [
                $type
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                PUSH PARAMETER $type
                INVOKE $isType WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '60013801B03DE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $parameter: [
            $parameters: [
                $key
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                PUSH PARAMETER $key
                INVOKE $parameter WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '60013801B052E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $parameters: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $parameters WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A853E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $supportsInterface: [
            $parameters: [
                $interface
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                PUSH PARAMETER $interface
                INVOKE $supportsInterface WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '60013801B07BE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
        $type: [
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $type WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A883E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
    ]
](
    $type: /bali/types/Compilation/v1
    $tag: #MYS8S7RGS8GXGYZP8S8DW96ALJSP8KKR
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
