[
    $description: "
        This abstract class defines the procedures for the messages that all components support.
    "($mediatype: "application/bsmd")
    $constants: [:]
    $procedures: [
        $isParameterized: [
            $description: "
                This procedure determines whether or not this component is parameterized.
            "($mediatype: "application/bsmd")
            $type: /bali/elements/Probability/v1($granularity: $boolean)
            $source: {
                return isParameterized(target)
            }
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $isParameterized WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A83CE000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
        ]
        $parameter: [
            $description: "
                This procedure returns a catalog of any parameters that were used to parameterize
                this component.
            "($mediatype: "application/bsmd")
            $type: /bali/abstractions/Element/v1
            $source: {
                return parameter(target, key)
            }($key: /bali/elements/Symbol/v1)
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                PUSH PARAMETER $key
                INVOKE $parameter WITH 2 ARGUMENTS
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '60013801B052E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $parameters: [
                $key
            ]
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
        ]
        $parameters: [
            $description: "
                This procedure returns a catalog of any parameters that were used to parameterize
                this component.
            "($mediatype: "application/bsmd")
            $type: /bali/collections/Catalog/v1(
                $keyType: /bali/elements/Symbol/v1
                $valueType: /bali/abstractions/Element/v1
            )
            $source: {
                return parameters(target)
            }
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $parameters WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A853E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
        ]
        $type: [
            $description: "
                This procedure returns the name of the type of this component.
            "($mediatype: "application/bsmd")
            $type: /bali/elements/Name/v1
            $source: {
                return type(target)
            }
            $instructions: "
                1.ReturnStatement:
                LOAD VARIABLE $target
                INVOKE $type WITH 1 ARGUMENT
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '6001A883E000'(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
            $addresses: [
                "1.ReturnStatement": 1
            ]
            $parameters: []
            $variables: [
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: []($type: /bali/collections/Set/v1)
        ]
    ]
    $literals: []
](
    $name: /bali/abstractions/Component/v1
    $type: /bali/abstractions/Class/v1($existence: $abstract)
    $tag: #GC5TG7QPT80BM6243Z15SKR0NB59KD94
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
