[
    $literals: [
        $ancestors
    ]
    $constants: [:]
    $procedures: [
        $getAncestry: [
            $parameters: []
            $variables: [
                $ancestor
                $ancestors
                $$index-2
                $$location-1
                $parent
                $$result
                $target
            ]($type: /bali/collections/Set/v1)
            $messages: [
                $addItem
                $getSubcomponent
            ]($type: /bali/collections/Set/v1)
            $addresses: [
                "1.EvaluateStatement": 1
                "2.EvaluateStatement": 3
                "3.EvaluateStatement": 9
                "4.WhileStatement": 11
                "4.1.ConditionClause": 12
                "4.1.1.EvaluateStatement": 14
                "4.1.2.EvaluateStatement": 20
                "4.ConditionRepeat": 32
                "4.WhileStatementDone": 33
                "5.ReturnStatement": 34
            ]
            $instructions: "
                1.EvaluateStatement:
                INVOKE $list
                STORE VARIABLE $ancestors
                
                2.EvaluateStatement:
                PUSH LITERAL `$ancestors`
                INVOKE $list
                LOAD VARIABLE $target
                INVOKE $addItem WITH 2 ARGUMENTS
                SEND $addItem TO COMPONENT WITH ARGUMENTS
                STORE VARIABLE $$result
                
                3.EvaluateStatement:
                LOAD VARIABLE $parent
                STORE VARIABLE $ancestor
                
                4.WhileStatement:
                SKIP INSTRUCTION
                
                4.1.ConditionClause:
                LOAD VARIABLE $ancestor
                JUMP TO 4.WhileStatementDone ON FALSE
                
                4.1.1.EvaluateStatement:
                LOAD VARIABLE $ancestors
                INVOKE $list
                LOAD VARIABLE $ancestor
                INVOKE $addItem WITH 2 ARGUMENTS
                SEND $addItem TO COMPONENT WITH ARGUMENTS
                STORE VARIABLE $$result
                
                4.1.2.EvaluateStatement:
                LOAD VARIABLE $ancestor
                LOAD VARIABLE $ancestor
                STORE VARIABLE $$location-1
                LOAD DOCUMENT $$location-1
                LOAD VARIABLE $parent
                STORE VARIABLE $$index-2
                INVOKE $list
                LOAD VARIABLE $$index-2
                INVOKE $addItem WITH 2 ARGUMENTS
                SEND $getSubcomponent TO COMPONENT WITH ARGUMENTS
                INVOKE $areEqual WITH 2 ARGUMENTS
                STORE VARIABLE $$result
                
                4.ConditionRepeat:
                JUMP TO 4.1.ConditionClause
                
                4.WhileStatementDone:
                SKIP INSTRUCTION
                
                5.ReturnStatement:
                LOAD VARIABLE $ancestors
                HANDLE RESULT
            "($mediatype: "application/basm")
            $bytecode: '
                A04D80022801A04D6007B001C8018006600580010000600118216002A04D
                6001B001C8018006600160018004780460058003A04D6003B001C802B008
                8006000C00006002E000
            '(
                $encoding: $base16
                $mediatype: "application/bcod"
            )
        ]
    ]
](
    $type: /bali/types/Compilation/v1
    $tag: #890V6V443DJHKRF30CXRKVJYHNDX3VWH
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
