[
    $description: "
        This abstract structure defines the attributes and messages that all types support.
    "($mediatype: "application/bsmd")
    $parent: /bali/abstractions/Composite/v1
    $constants: [:]
    $parameters: [
        $existence: [
            $description: "
                This parameter describes whether this type is concrete and can be instantiated
                or if it is abstract and cannot.
            "($mediatype: "application/bsmd")
            $type: /bali/enumerations/Existence/v1
            $default: $concrete
        ]
    ]
    $attributes: [
        $description: [
            $description: "
                This attribute describes the purpose for a component.
            "($mediatype: "application/bsmd")
            $type: /bali/elements/Text/v1($mediatype: /bali/elements/Text/v1)
        ]
        $parent: [
            $description: "
                A reference to the parent type from which this type inherits its behavior.
            "($mediatype: "application/bsmd")
            $type: /bali/elements/Reference/v1($referencedType: /bali/abstractions/Type/v1($existence: $abstract))
        ]
        $parameters: [
            $description: "
                A catalog of the parameters that are used to parameterize instances of this type.
            "($mediatype: "application/bsmd")
            $type: /bali/collections/Catalog/v1($valueType: /bali/composites/Parameter/v1)
        ]
    ]
    $procedures: [:]
    $literals: []
](
    $name: /bali/abstractions/Type/v1
    $type: /bali/abstractions/Structure/v1($existence: $abstract)
    $tag: #Z2RZ1550HK9HSW6QVVP6WTAA55P31ZQX
    $version: v1
    $permissions: /bali/permissions/public/v1
    $previous: none
)
